{% set python_min = '3.10' %}
{% set name = "foundry-dev-tools-transforms" %}
{% set version = "2.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/foundry_dev_tools_transforms-{{ version }}.tar.gz
  sha256: c4dd784d38bc81b7173955135a44a16a4d1b2f7ee78eda4c6af10419bb7ef210

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - foundry-dev-tools
    - typing_extensions
    - pyspark >=3.0.0
    - numpy <2
    - fs

test:
  imports:
    - transforms
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/emdgroup/foundry-dev-tools
  summary: Seamlessly run your Palantir Foundry Repository transforms code on your local machine.
  dev_url: https://github.com/emdgroup/foundry-dev-tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonas-w
    - nicornk
